# Orquestrador Modular do GitLab CI/CD (com DevSecOps Security Pipeline)

default:
  tags:
    - oracle-vps

stages:
  - security-scan
  - test
  - build
  - docker-build
  - docker-security
  - deploy

# Inclusão dos Módulos Especializados de CI/CD & Segurança
include:
  - local: '.gitlab/ci/security.gitlab-ci.yml'
  - local: '.gitlab/ci/test.gitlab-ci.yml'
  - local: '.gitlab/ci/build.gitlab-ci.yml'
  - local: '.gitlab/ci/docker.gitlab-ci.yml'
  - local: '.gitlab/ci/deploy.gitlab-ci.yml'

