# Orchestrador Modular do GitLab CI/CD

stages:
  - test
  - build
  - docker-build

# Inclusão dos Módulos Especializados de CI/CD
include:
  - local: '.gitlab/ci/test.gitlab-ci.yml'
  - local: '.gitlab/ci/build.gitlab-ci.yml'
  - local: '.gitlab/ci/docker.gitlab-ci.yml'
