# Módulo de Compilação estática do Vite SPA

build_frontend:
  image: node:lts-alpine
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
